= Version 3.0.20
[horizontal]
Release date:: November 2025
* Date of member review: 2025-09-15
* Date of publication: 2025-11-24
* Mandatory to use from: 2026-02-23

== Changes to BIS document


== Changes to code lists and validation artefacts

Codelist publication date: 2025-09-05
Validation artefacts publication date: 2025-10-03

[cols="1,1,1"]
|===
|codelist|removed|added

|===


==  EN 16931 schematrons updated

* NEW common rule R052 added to check for valid Danish chamber of commerce number (P) using test: (string-length(string()) = 8) and (string-length(translate(string(), '1234567890', '')) = 0)
  ** https://openpeppol.atlassian.net/browse/RFC-491

* NEW Common rule R053 added check for valid ERSTORG number (SE): (string-length(string()) = 10) and (substring(string(), 1, 2) = 'SE') and (string-length(translate(substring(string(), 3, 8), '1234567890', '')) = 0)
  ** https://openpeppol.atlassian.net/browse/RFC-491
  
* Common rule R048 CII commented out, simular to the UBL

* Updated companion test files

* Resolved the issue "A function that computes atomic values should use xsl:sequence rather than xsl:value-of"

==  Changes to Country-Specific Rules
* BUG Rule DK-R-010 
  fixed the text from: For Danish Suppliers the PaymentID is mandatory and MUST start with 71#, 73# or 75# (kortartkode) and CreditAccount/AccountID (Kreditornummer) is mandatory and MUST be exactly 8 characters long, when Payment means equals 93 (FIK)
  to: For Danish Suppliers using PaymentMeansCode 93, PaymentID is mandatory. The first three characters of the PaymentID MUST be 71#, 73# or 75# (kortartskode), and PayeeFinancialAccount/ID MUST be exactly 8 characters long.

* NEW Fatal Rule DK-R-017
  For Danish Customers it is mandatory to specify schemeID as "0184" (DK CVR-number) when PartyLegalEntity/CompanyID is used for AccountingCustomerParty
  ** context: supplier and customer country is "DK"
  ** rule: not(((boolean(cac:PartyLegalEntity/cbc:CompanyID)) and (normalize-space(cac:PartyLegalEntity/cbc:CompanyID/@schemeID) != '0184')))

