= Version 3.0.17
[horizontal]
Release date:: May 2024

== Changes to BIS document

None

== Changes to code lists and validation artefacts

* Added new Swedish rule (SE-R-013) for validation of the check number of a Swedish Organization number. The rule is introduced as severity warning. All rules which verify the format of Organization numbers (SE-R-003, SE-R-004 and SE-R-013) will be changed to severity fatal in the next release.
* Update for rule NL-R-007 (mandatory payment means), the check should not fire if the document is a credit note with a positive amount.
* Update of PEPPOL-COMMON-R049, which validates identifiers using ICD/EAS 0007. The change is adding validation of the check number of a Swedish Organization number.
* Removing Currency code Sierra Leone SLL, new code is SLE
* Adding Payment means code 98
* Adding Item type identification code GMN
* Adding charge code PRV
* Adding VAT Exemption reason codes VATEX-FR-FRANCHISE, VATEX-FR-CNWVAT

==  EN 16931 schematrons updated
* Changes in the code lists supported
* BT-32 path check missing in BR-AE-02, BR-AE-03, and BR-AE-04 in CII
* [BR-63] fails if multiple URIUniversalCommunication are present
* BR-33 / BR-CO-21 rules validation doesn't work on CII files (OK on UBL files)
* Undocumented and missing changes in v.1.3.11 release
* missing cardinality check for Value added tax point date (BT-7) and Value added tax point date code (BT-8) in CII
