= Version 3.0.18
[horizontal]
Release date:: November 2024

== Changes to BIS document

== Changes to "BIS compliance" document
* Added new compliance rules on how to use sender/receiver identifiers when enveloping a BIS3 message in Peppol Business Message Envelope (SBDH) 

== Changes to code lists and validation artefacts

* German country specific validation rules added.
* The rule (PEPPOL-EN16931-R002), which ensures that the Invoice Note (BT-22) appears no more than once, will not apply if both the buyer and seller are German organizations.
* Update for country-specific rule NL-R-008 Make rule domestic-only.
* sample files and snippits have been updated to reflect the new rule PEPPOL-EN16931-R131
* Severity of Swedish country specific rules SE-R-003, SE-R-004 and SE-R-013 which verifies format of Swedish organization numbers are changed from warning to fatal.

[attributes]
====
    <cac:ExternalReference>
        <cbc:URI>http://www.techspec.no</cbc:URI>
    </cac:ExternalReference>
====


==  EN 16931 schematrons updated

* new fatal rule PEPPOL-EN16931-R131 on Document referenced by URI, only allows content starting with http(s):// or ftp(s)://