= Version 3.0.14
[horizontal]
Release date:: 2022-11-01

== Changes to BIS document
* Editorial change in the documentaion templates. Many pages in previous releases had a "Last updated" timestamp in the page footer. The timestamp indicated when the HTML-page was generated by the documentation tool, not when the actual content of the page was updated/changed. The timestamp is now removed since it caused a lot of confusion. 
* Example files added to zip-file that can be downloaded from the main page of the BIS.

== Changes to code lists and validation artefacts
* Rule PEPPOL-COMMON-R049 (ICD 0007 - Swedish organization number) changed from severity warning to fatal (as announced in the may 2022 release)
* Correction in Rule PEPPOL-COMMON-R050 (validation of Australian Business Number (ABN)) corrected
* Adopted EN 16931 validation artefacts release 1.3.9
** Added EAS codes 9959
** Removed EAS codes 9906 and 9907
** Added ICD codes 0217, 0218, 0219 and 0220
** Correction to validation rules as listed https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.9

==  Changes to Country-Specific Rules

* Rules GR-S-008-1, GR-R-008-2 and GR-R-008-3 have been updated, expecting the string \##INVOICE|URL## instead of \##INVOICE-URL## (POAC-518)
* Rule DK-R-015 removed
* Error text changes to DK-R-004 PEPPOL CII rules
* Error text changes to DK-R-003 Peppol CII rules