= Version 3.0.20
[horizontal]
Release date:: November 2025
* Date of member review: 2025-09-15
* Date of publication: 2025-11-24
* Mandatory to use from: 2026-02-23

== Changes to BIS document

* Compliance section on binary objects updated with removal of the following text: "The attachment functionality is not intended for of including a copy of the invoice in an image format (such as PDF). Attaching an invoice copy is not in compliance with this specification."

== Changes to code lists and validation artefacts

* Codelist publication date: 2025-10-23
* Validation artefacts UBL and CII 1.3.15 publication date: 2025-10-23

[cols="1,1,1"]
|===
|codelist|removed|added
|eas |0 [] |1 [0244]
|icd |0 [] |4 [0241,0242,0243,0244]
|ISO4217 |1 [STN] |2 [CNH,STD]
|VATEX |0 [] |1 [VATEX-EU-135-1]
|===

For the Country code BS (Bahamas), the country name has been changed from "Bahamas" to "Bahamas (The)" in accordance with the ISO 3166-1 standard.

* Added rule PEPPOL-COMMON-R052, which checks that the Danish Chamber of Commerce number (P) consists of exactly ten characters and contains only digits.
  ** https://openpeppol.atlassian.net/browse/RFC-491
  ** rule is initially a warning and consecutive release fatal

* Added rule PEPPOL-COMMON-R053, which checks that the Danish ERSTORG number (SE) is ten characters long, starts with “DK”, and that the remaining characters are digits.
  ** https://openpeppol.atlassian.net/browse/RFC-491
  ** rule is initially a warning and consecutive release fatal

* Rule PEPPOL-COMMON-R084 removed since it is not used anymore

* Updated companion test files

* Resolved the issue “A function that computes atomic values should use xsl:sequence rather than xsl:value-of”, as using xsl:value-of in some contexts can cause warnings or errors in some XSLT parsers.

==  EN 16931 schematrons updated

* Update codes in code lists
* Restored missing example files
* CII Wrong calculation for rules BR-IC-08, BR-G-08, BR-E-08 and BR-AE-08
* UBL-CR-628 and UBL-CR-631 are identical
* The IDs of some of the new Business Rules of the upcoming EU EN 16931 are already taken by Validator Rules
* BT-86 missing validation in CII
* Adopt new codes into Schematrons
* Added rules CII-SR-465 and CII-SR-466

==  Changes to Country-Specific Rules
* BUG Rule DK-R-010 
  fixed the text from: For Danish Suppliers the PaymentID is mandatory and MUST start with 71#, 73# or 75# (kortartkode) and CreditAccount/AccountID (Kreditornummer) is mandatory and MUST be exactly 8 characters long, when Payment means equals 93 (FIK)
  to: For Danish Suppliers using PaymentMeansCode 93, PaymentID is mandatory. The first three characters of the PaymentID MUST be 71#, 73# or 75# (kortartskode), and PayeeFinancialAccount/ID MUST be exactly 8 characters long.

* NEW Fatal Rule DK-R-017
  For Danish Customers it is mandatory to specify schemeID as "0184" (DK CVR-number) when PartyLegalEntity/CompanyID is used for AccountingCustomerParty
  ** rule is initially a warning and consecutive release fatal
  ** context: supplier and customer country is "DK"
  ** rule: not(((boolean(cac:PartyLegalEntity/cbc:CompanyID)) and (normalize-space(cac:PartyLegalEntity/cbc:CompanyID/@schemeID) != '0184')))

