= Version 3.0.1 - hotfix
[horizontal]
Release date:: 2018-04-20

== Changes to BIS document

* Correct calculation formula in chapter 9.1.1, see link:https://github.com/OpenPEPPOL/peppol-bis-invoice-3/issues/46[Github issue 46]

== Changes to syntax mapping tables

* Correct the structure of the `cac:Taxtotal` element in the syntax mapping.
* Add EN16931 rules to syntax mapping.
* Cardinality set to mandatory for element `cac:InvoiceDocumentReference` as this is the only element in `cac:BillingReference`
* Cardinality set to mandatory for element `cbc:URI` as this is the only element in `cac:AdditionalDocumentReference/cac:Attachment/cac:ExternalReference`
* Change description text from "Document level..." to "Line level..." for allowance/charge elements on line level in the syntax mapping table.

== Changes to validation artefacts

* Removed rule "PEPPOL-EN16931-R050 - Tax exemption reason code MUST NOT be used"
* Incorporated updated validation artifacts from TC434 (amongst other, adding new ICD values).
