= Version 3.0.21
[horizontal]
Release date:: May 2026
* Date of member review: 2026-03-02
* Date of publication: 2026-05-18
* Mandatory to use from: 2026-08-24

== Changes to BIS document

* Corected the naming where it occured to Peppol instead of PEPPOL. 
* New optional profile added for a process where an invoice response is required step in the collaboration. The profile (02) requires a separate SMP registration. The same profile identifier has been added to the Invoice Response BIS.

== Changes to code lists and validation artefacts
* Codelist publication date: 2026-03-06
* Validation artefacts UBL and CII 1.3.15 publication date: 2026-04-10

* Rule PEPPOL-EN16931-P0100 and PEPPOL-EN16931-P0101 which checks for valid invoice type codes are updated so that the rules also takes the new profile 02 (billing with response) into consideration.
* New optional tests to check SBDH compliance added to download page
* Texts for Peppol rules are now prefixed with rule identifier
* Changed rule PEPPOL-COMMON-R052 and PEPPOL-COMMON-R053 to be errors instead of warnings, as the rules are now mandatory for all profiles.

[cols="1,1,1"]
|===
|codelist|removed|added
|===


==  EN 16931 schematrons updated

* Fatal rule PEPPOL-EN16931-R004 in UBL and CII schematron updated to reflect the correct requirement for CustomizationID without version information.
  ** Added new tests to test file to check if version information is included in CustomizationID and provide appropriate error message. 

* New warning rules for Dutch identifiers with scheme 0106, 0190, 0217, 9944, and NL VAT numbers added to UBL and CII schematrons:
  ** PEPPOL-COMMON-R054: Identifiers with scheme 0106 should be 8 digits
  ** PEPPOL-COMMON-R055: Identifiers with scheme 0190 should be 20 digits
  ** PEPPOL-COMMON-R056-1: Identifiers with scheme 9944 should have the format NL123456789B12
  ** PEPPOL-COMMON-R056-2: VAT identifiers starting with NL should have the format NL123456789B12
  ** PEPPOL-COMMON-R057: Identifiers with scheme 0217 should be 20 digits
  ** rules will become fatal in future release, but are warnings in this release to allow for transition period for implementers to update their systems and data.

==  Changes to Country-Specific Rules



== Other changes

* Updated stylesheet and added html for testing the stylesheet.
