= Version 3.0.16
[horizontal]
Release date:: November 2023

== Changes to BIS document

* A recommendation has been added to the Sales Order Reference element for handling cases where there is no Purchase Order Reference. This clarifies what to do with the mandatory UBL element for Purchase Order Reference. Example file is added which illustrates this.

* Text in section 4.6 on negative invoices edited to remove historic comparison to BIS2 and justification for the change. No functional change.

== Changes to code lists and validation artefacts

* The validation rule identified as PEPPOL-EN16931-R006, which ensures that only one Invoice Object is allowed at the document level in an invoice/credit note, has been removed. This is because it duplicates the European standard rule UBL-SR-04, making it redundant and unnecessary.

* The structure of the Peppol Schematron rule set has been improved for better quality. A function that was previously located in the Greek rules section is now correctly positioned alongside other functions.

==  EN 16931 schematrons updated
* Adopted version 1.3.11 of EN 16931 validation artefacts (# numbers refer to EN GitHub issues).
** Cardinality of DesignatedProductClassification in CII might stop the check BR-65 #355
** CII Missing check on DefinedTradeContact cardinality #354
** CII BT-17 and BT-18 checks to be improved #353
** UBL-SR-43 using attribute scheme instead of schemeID #351
** CII - missing cardinality check for ApplicableTradeTax (BG-30) #349
** Error in Validation of Rule BR-E-08 #348
** UBL-SR-51 does not check cac:DeliveryLocation #347
** Typo in rule-text UBL-CR-282, UBL-CR-247 and UBL-CR-183 (UBL) #346
** Typo in rule-text UBL-CR-583, UBL-CR-577 and UBL-CR-572 (UBL) #345
** BR-17 rule checks too hard? #344
** CII - missing cardinality check for SpecifiedTradePaymentTerms #343
** add missing currency codes #356
** Add EAS Code 0218 list #359
