= Version 3.0.3
[horizontal]
Release date:: 2019-05-15


== Changes to BIS document and validation artifacts
* Adopted versions 1.2 and 1.2.1 of EN 16931 validation artifacts (includes new codes and rules)
* VAT specified in separate currency now have the same operational sign as the VAT	POACC-172
* Added rule to check format of ProfileID (Process identifier)	POACC-179
* Added rule to check that only values true/false are used in AllowanceCharge/ChargeIndicator	POACC-98
* Floating point error when comparing decimals in some implementations. All use of the xpath function sum() adjusted/verified. (Both Billing and BIS Order/OrderAgreement)	POACC-184
* Linebreaks and other whitespace inside rule statements removed for the PEPPOL-rules (not country specific)	POACC-158
* Codes 0198 (ERSTORG), 0199 (GLEIF), 0200 (Lithuania org code) added as allowed Electronic Address schemes
* Added a common structure validation rule for Norwegian organizational numbers and GLN numbers.
* Various text corrections and minor bug fixes.

== Changes in validation rules inherited through adoption of EN 16931 validation artifacts version 1.2 and version 1.2.1
* A slack allowed in calculation of amounts to reduce disruption from rounding issues.
* ICD scheme codes 0198 (ERSTORG), 0199 (GLEIF), 0200 (Lithuania org code) added and 9902, 9904, 9905 removed (all DK)
* For further details on changes inherited from version 1.2 see https://github.com/CenPC434/validation/issues?q=is%3Aissue+is%3Aclosed+milestone%3Av1.2
* For further details on changes inherited from versoin 1.2.1 see https://github.com/CenPC434/validation/issues?q=is%3Aissue+is%3Aclosed+milestone%3Av1.2.1

== Updated national rules
* PEPPOL BIS Billing Italian validation rules updated	POACC-180
* PEPPOL BIS Billing Danish validation rules (UBL and CII) updated	POACC-178
