= Version 3.0.18
[horizontal]
Release date:: November 2024

== Changes to BIS document


== Changes to code lists and validation artefacts

* Invoice Type codes 326 (Partial invoice) and 384 (Corrected invoice) added to the codelist and listed as synonyms with type code 380 (Commercial Invoice)
* German country specific validation rules added.
* The rule (PEPPOL-EN16931-R002), which ensures that the Invoice Note (BT-22) appears no more than once, will not apply if both the buyer and seller are German organizations.
* Update for rule NL-R-008 (mandatory payment means), the check should not fire if the document is a credit note with a positive amount.
* sample files and snippits have been updated to reflect the new rule PEPPOL-EN16931-R131
            <cac:ExternalReference>
                <cbc:URI>http://www.techspec.no</cbc:URI>
            </cac:ExternalReference>

==  EN 16931 schematrons updated

* new fatal rule PEPPOL-EN16931-R131 on Document refenced by URI, only allows content starting with http(s):// or ftp(s)://