= Version 3.0.18
[horizontal]
Release date:: November 2024

== Changes to BIS document

== Changes to Compliance BIS document
* Added new compliance on SBDH and BIS3 payload
** The value of the SBDH element "Sender/Identifier" MUST be equivalent to the value in the sender party’s "Party/EndpointID" element and its "schemeID" attribute.
** The value of the SBDH element "Receiver/Identifier" MUST be equivalent to the value in the receiver’s party "Party/EndpointID" element and its "schemeID" attribute

== Changes to code lists and validation artefacts

* Invoice Type codes 326 (Partial invoice) and 384 (Corrected invoice) added to the codelist and listed as synonyms with type code 380 (Commercial Invoice)
* German country specific validation rules added.
* The rule (PEPPOL-EN16931-R002), which ensures that the Invoice Note (BT-22) appears no more than once, will not apply if both the buyer and seller are German organizations.
* Update for country-specific rule NL-R-008 Make rule domestic-only.
* sample files and snippits have been updated to reflect the new rule PEPPOL-EN16931-R131
* Severity of Swedish country specific rules SE-R-003, SE-R-004 and SE-R-013 which verifies format of Swedish organization numbers are changed from warning to fatal.

[attributes]
====
    <cac:ExternalReference>
        <cbc:URI>http://www.techspec.no</cbc:URI>
    </cac:ExternalReference>
====


==  EN 16931 schematrons updated

* new fatal rule PEPPOL-EN16931-R131 on Document referenced by URI, only allows content starting with http(s):// or ftp(s)://