= Version 3.0.15
[horizontal]
Release date:: 2023-05-01

== Changes to BIS document


== Changes to code lists and validation artefacts

* Rule PEPPOL-COMMON-R050 (validation of Australian Business Number (ABN)) changed from severity warning to fatal (as announced in earlier release)
* Adopted EN 16931 validation artefacts release 1.3.10
** Added EAS codes 0221, 0230
** Removed EAS codes 9955
** Added ICD codes 0221, 0222, 0223, 0224, 0225, 0226, 0227, 0228, 0229, 0230
** Added Item type identification code (CL7143) EMD (EMDN (European Medical Device Nomenclature))
** Correction to validation rules as listed https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.10

==  Changes to Country-Specific Rules
* Removed Rules GR-R-007-1, GR-R-007-2 and GR-R-007-3
* Changed application context in rules GR-R-004-1 and GR-R-004-2: Rules do not apply now when Tax Representative is Greek
* Added Rule GR-R-011 making the Greek Tax Identification Number Mandatory for the supplier
* Renamed rule GR-R-011 to GR-S-011 and changed from fatal to warning
