= Version 3.0.5
[horizontal]
Release date:: 2019-11-01

== Changes to BIS document

* A description in BIS for a workaround for UNSPSC codes as item classification codes, removed since a new code has been added to code list UNECE 7143, directly supporting UNSPSC. This new code is TST.
* Description of EAS code for code ION 0190 corrected. No change to the code itself.

== Changes to support documents

* Syntax mapping between UBL and CII, in xls spreadsheet corrected. Mapping for BT-34 corrected to use URIID instead of GlobalID. Correction in line with part 3-3 of EN 16931. Published in new version of mapping in file mapping-cii-ubl v2 fr19.xls
* A bug in xslt stylesheet fixed. The stylesheet contains a list (uncl1001invoice) of different document types, that is displayed. In this list, only the Invoice name exist while the creditnote name is did not exist.

== Changes to code lists and validation artefacts

* Update in link:/poacc/billing/3.0/codelist/eas/[EAS] code list, addition of codes: 0130 and 0204, and deprecating of code 9902, 9904, 9905, 9917 and 9921.
* Update in link:/poacc/billing/3.0/codelist/ICD/[ICD] code list, addition of codes: 0203 and 0204. Description of code 0190 corrected as specified in ICD code certificate.
* Update in link:/poacc/billing/3.0/codelist/vatex/[VATEX] code list, addition of codes: vatex-eu-132, vatex-eu-143, vatex-eu-148, vatex-eu-151
* Rule PEPPOL-EN16931-CL005 "Country code MUST be according to ISO 3166 Alpha-2" deleted since it is an unneccessary duplication of [BR-CL-14]-"Country codes in an invoice MUST be coded using ISO code list 3166-1"
* Rule PEPPOL-EN16931-R008 has been updated and PEPPOL-EN16931-R009 has been removed.
* Error message for rules rephrased to be more instructive. Rules themselves are unchanged.
** PEPPOL-COMMON-R040: "Invalid GLN number provided." -> "GLN must have a valid format according to GS1 rules."
** PEPPOL-COMMON-R041: "Invalid Norwegian organization number provided." -> "Norwegian organization number MUST be stated in the correct format."
** PEPPOL-EN16931-CL001: "Invalid mime code." -> "Mime code must be according to subset of IANA code list."
* An error in a common structural validation of GLN numbers, rule PEPPOL-COMMON-R040, corrected.
* Changed implementation of empty element-test. Rule updated so that it also fails on whitespace only content.
* Country rules for Denmark updated.
* Added rule PEPPOL-COMMON-R042 to check structure of Danish CVR numbers.
* Danish country rule DK-R-003 changed to use scheme code TST instead of MP for identifying UNSPSC classification.
* PEPPOL rul PEPPOL-COMMON-R002 removed and PEPPOL-COMMON-R001 modified to cover its functionality.

* Changes to TC434 rules as link:https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.0[released here.]
