
= Use case 2

On behalf of many municipalities or governmental entities a central unit has been given the task to accomplish a tender for the group on office supplies.

The call for tender includes a structured pre-award catalogue request with the needs for the group. The economic operator (supplier) that prepares the tender downloads or receive the catalogue request as part of the tendering documents. The pre-award catalogue request is containing descriptions of product and services the group needs in a generic way, e.g. blue pen.

Supplier choose their own products or services that fulfills the requirement and make use of a supplier eSubmission system to fill out the requested information as product number, product description, UoM (unit of measure) code, price, link to pictures and labels for environmental and social labels if required and so on. They can reuse generic information the central unit has included in the pre-award catalogue request as classification codes as UNSPSC, CPV or eCl@ss.

After finalizing the pre-award catalogue they include the catalogue together with other structured documents as ESPD or non-structured documents as PDF in to the system. The system prepares for submission towards the tender systems by sending the bid package to the access point connected.

When contracting authority receive, through their access point, the pre-award catalogues from different suppliers, as part of the bid packages they lock down the offers. When time for open the bids, tendering system import the pre-award catalogue xml files in to their valuation service and find the best offer of products and/or services.

The central unit import the catalogue into their catalogue tool and check the quality. According to the contract the supplier is sending a post-award catalogue that’s compared towards the pre-award catalogue from the tender. When the catalogue is ok the central unit sends it out of their access point, based on a distribution list in the catalogue tool. The different municipalities or governmental entities is receiving the approved pre-award catalogue in their catalogue tool connected to their eProcurement system. When the catalogue already is approved, the system can automatically display the catalogue content in the eProcurement search engine used by the different entities buyers.
