= Roles and Actor

The following roles may be specified. The same actor may play more than one role depending on the handling routine.

Seller (AccountingSupplierParty)::
Seller is mandatory information.

Buyer (AccountingCustomerParty)::
Buyer is mandatory information.

Payment receiver (PayeeParty)::
Payment receiver is optional information. If this information is not supplied, the seller is the payment receiver.

Sellers Tax Representative (TaxRepresentativePary)::
Tax representative party for the seller is relevant for sellers delivering goods and services in a country without having a permanent establishment in that country. In such cases information on the tax representative shall be included in the invoice.

[source, xml]
.Example: Supplying seller information on the header level.
----
<cac:AccountingSupplierParty>
    <cac:Party>
        <cbc:EndpointID schemeID="0002">1234567</cbc:EndpointID>
        <cac:PostalAddress>
            <cbc:StreetName>Postbus 7l</cbc:StreetName>
            <cbc:CityName>Velsen-Noord</cbc:CityName>
            <cbc:PostalZone>1950 AB</cbc:PostalZone>
            <cac:Country>
                <cbc:IdentificationCode>NL</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyTaxScheme>
            <cbc:CompanyID>NL8200.98.395.B.01</cbc:CompanyID>
            <cac:TaxScheme>
                <cbc:ID>VAT</cbc:ID>
            </cac:TaxScheme>
        </cac:PartyTaxScheme>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>De Koksmaat</cbc:RegistrationName>
            <cbc:CompanyID>57151520</cbc:CompanyID>
        </cac:PartyLegalEntity>
    </cac:Party>
</cac:AccountingSupplierParty>
----


[source, xml]
.Example: Supplying buyer information on the header level
----
<cac:AccountingCustomerParty>
    <cac:Party>
        <cac:PartyIdentification>
            <cbc:ID>10202</cbc:ID>
        </cac:PartyIdentification>
        <cac:PostalAddress>
            <cbc:StreetName>POSTBUS 367</cbc:StreetName>
            <cbc:CityName>HEEMSKERK</cbc:CityName>
            <cbc:PostalZone>1960 AJ</cbc:PostalZone>
            <cac:Country>
                <cbc:IdentificationCode>NL</cbc:IdentificationCode>
            </cac:Country>
        </cac:PostalAddress>
        <cac:PartyLegalEntity>
            <cbc:RegistrationName>ODIN 59</cbc:RegistrationName>
        </cac:PartyLegalEntity>
        <cac:Contact>
            <cbc:Name>Dhr. J BLOKKER</cbc:Name>
        </cac:Contact>
    </cac:Party>
</cac:AccountingCustomerParty>
----
