
= Allowances and Charges, General Rules

. Several allowances and charges may be supplied both on header level and line level. For the price only one occurence of allowance (discount) is allowed.
The element `cac:AllowanceCharge` with sub element `cbc:ChargeIndicator` indicates whether the instance is a charge (true) or an allowance (false).
. Specification of VAT for allowances and charges, `cac:TaxCategory` with sub elements,  may be supplied both on the header level and on the line level, but not for the `cac:Price` element.
. The sum of all allowances and charges on the header level must be specified in `cbc:AllowanceTotalAmount` and `cbc:ChargeTotalAmount` respectively. See <<totals>>
. The sum of all allowances and charges on the line level must be taken into account, subtracted or added, when calculating the line extension amount . These line level allowances and charges must not be calculated into the header level elements.
. Allowances related to Price shall not be part of any other calculations.
. Allowances related to Price may specify amount and the base amount.

== Invoice and credit note

The Invoice and credit note transactions has elements for Allowance/charge on 3 levels:

. *The header level*, applies to the whole invoice and is included in the calculation of the invoice total amount.
. *The line level*, applies to the line level and is included in the calculation of the line amount.
. *The line level Price element*, a way to inform the buyer how the price is set. Is also relevant if the seller or buyer want to post the allowance in their accounting systems.  The price itself shall always be the net price, i.e. the base amount  reduced with a discount (allowance).


.XML for Allowances and Charges on the document level
[source, xml, indent=0]
----
include::../snippets/Snippet-refs.xml[tags=allowance]
----
<1> ChargeIndicator = true to indicate a charge
<2> ChargeIndicator = false to indicate an allowance
