[[element-codes]]
= Code lists for coded elements


.Code lists used in the invoice and credit note
[cols="2,1,3", options="header"]
|====
|Business term
|Applicable XPath
|Code list

| Invoice Type Code
a| cbc:InvoiceTypeCode

cbc:CreditNoteTypeCode
a| Subset of link:http://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred1001.htm[UN/CEFACT code list 1001, D.16B]

| Currency codes
a|
cbc:DocumentCurrencyCode

cbc:TaxCurrencyCode

cbc:*[@currencyID]

a| link:https://www.iso.org/iso-4217-currency-codes.html[ISO 4217:2015]

| Value added tax point date code
| /cac:InvoicePeriod/cbc:DescriptionCode
a| Subset of link:http://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred2005.htm[UN/CEFACT code list 2005, D.16B]

.Valid values
[horizontal]
3::     Invoice document issue date time
35::    Delivery date/time, actual
432::   Paid to date

| Invoice note subject code
| cbc:Note
a| link:http://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred4451.htm[UN/CEFACT code list 4451, D.16B]

| Country codes
a|
cac:CountryCode/cbc:IdentificationCode

cac:InvoiceLine/cac:Item/cac:OriginCountry/cbc:IdentificationCode
a| link:http://www.iso.org/iso/home/standards/country_codes.htm[ISO 3166-1 #Alpha-2?#]


| Payment means type code
| cac:PaymentMeans/cbc:PaymentMeansCode
a| link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred4461.htm[UN/CEFACT code list 4461, D.16B]

| VAT category codes
a| cac:ClassifiedTaxCategory/cbc:ID

cac:TaxCategory/cbc:ID
a| Subset of link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5305.htm[UN/CEFACT code list 5305, D.16B]

.Valid values
[horizontal]
AE:: Vat Reverse Charge
E:: Exempt from Tax
S:: Standard rate
Z:: Zero rated goods
G:: Free export item, tax not charged
O:: Services outside scope of tax
K:: VAT exempt for EEA intra-community supply of goods and services
L:: Canary Islands general indirect tax
M:: Tax for production, services and importation in Ceuta and Melilla


| Allowance reason codes
| cbc:AllowanceChargeReasonCode (with cbc:ChargeIndicator=false)
a| link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5189.htm[UN/CEFACT code list 5189, D.16B]

| Charge reason codes
| cbc:AllowanceChargeReasonCode (with cbc:ChargeIndicator=true)
a| link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred7161.htm[UN/CEFACT code list 7161, D.16B]

|VAT exemption reason code
| cbc:TaxExemptionReasonCode
| #Code list issued and maintained by CEF??#

| Mime code of attached document
| cbc:EmbeddedDocumentBinaryObject[@mimeCode]
a| Subset of link:http://www.iana.org/assignments/media-types[IANA code list]

.Valid values

* application/pdf
* image/png
* image/jpeg
* text/csv
* application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
* application/vnd.oasis.opendocument.spreadsheet

| Invoiced quantity unit of measure code
| cbc:InvoicedQuantity/@unitCode
a| link:http://www.unece.org/cefact/recommendations/rec_index.html[UN/ECE Recommendation 20 and 21]

#Add version information?#

|====
