

= Introduction

== Principles

This migration plan is based on the following principles:

. To allow a smooth and as friction free transition as possible, using two versions of the element subject to migration to enable new as well as existing end‐users to prepare for an updated element must be allowed.

. To ensure non-disrupted operations and full interoperability of the messages exchanged in the Peppol network, the period during which two parallel versions are allowed should be as short as possible.

. Any changes affecting the current (mandatory) Peppol element should be notified, communicated and agreed upon in the relevant coordinating community (CC) well in advance.

. The migration is conducted in three steps at three different points in time, marked as “A”, “B” and “C” and defined as follows:

A – Phase-in:: date at which the Peppol BIS Billing 3.0 is introduced as an optional element. At this date it should be possible to download any specification for this Peppol BIS. Peppol BIS Billing 3.0 is optional at this point in time.

B – Transition:: the date at which the Peppol BIS Billing 3.0 becomes the mandatory element. The previously mandatory Peppol BIS Billing 5a (version 2.3) and Peppol BIS Billing 4a (version 2.3) become optional.

C – Phase out:: the date after which the Peppol BIS Billing 5a (version 2.3) which was mandatory at “A”, and became optional at “B”, is no longer supported or maintained by Peppol

****
[NOTE]
====
* The migration rules only apply to an *end user’s* individual Peppol BIS registered in the SMP.
* The migration rules only apply for a new Peppol BIS that updates or replaces an existing one.
* All Peppol participants shall adhere to the Migration Policy.
====
****
