
= Migration rules ‐ PEPPOL participants affected by the Migration Policy

This OpenPEPPOL BIS Billing Migration Policy affects all end-users registered in a SMP for invoice/billing according to the following rules:

.End-users registered in a SMP before the phase-in date ({phase-in})
****
Rule::
* It is mandatory to support the Peppol BIS Billing 5a (version 2.3) that are registered in the SMP for an individual end user, until the transition date ({transition}).
* Supporting Peppol BIS Billing 3.0 is optional until the transition date ({transition}).
****

.End-users registered in a SMP after the phase-in date ({phase-in})
****
Rule::
It is optional to support the Peppol BIS Billing 5a (version 2.3) or the Peppol BIS Billing 3.0 that are registered in the SMP for an individual end user until the transition date ({transition}).
****

.For all end-users after the transition ({transition})
****
Rule::
After the transition, the Peppol BIS Billing 3.0 becomes mandatory and the Peppol BIS Billing 5a (version 2.3) become optional.
****

.For all end-users after the Phase Out ({phase-out})
****
Rule::
OpenPEPPOL will no longer support the use of Peppol BIS 5a and 4a (version 2.3 or their older versions) in any way. This includes maintenance of validation artefacts and service desk support. Any further use of Peppol BIS 5a and 4a is strongly discouraged and done at the Service Providers’ own risk.
****