[preface]
= Introduction

This transaction specification is a detailed implementation guide for the invoice and credit note transactions, and this specification together with the profile documents, are a {CIUS} of {EN16931}, following the guidance given in chapter 7 of the {EN16931}. Any instance documents following this specification will always be compliant with the European Standard ({EN16931}).

== Scope

This document provide a detailed implementation guideline for the invoice and credit note transactions to be used by all invoice and credit note profiles in PEPPOL.


== Audience

The audience for this document is organisations wishing to be PEPPOL enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

* Service providers
* Contracting Authorities (CA)
* Economic Operators (EO)
* Software Developers

More specifically, roles addressed are the following:

* ICT Architects
* ICT Developers
* Business Experts

For further information on PEPPOL/OpenPEPPOL, please see {common}
