
= Negative invoices and credit notes


In line with requirements of {EN16931} this BIS supports negative grand totals. This represents a significant change in comparison to {openpeppol}’s previous specifications where invoices and credit notes have non-negative total.

The argument for negative invoices is to open up for a wider spectrum of invoicing processes.

Examples of such processes are

*	Preliminary (estimated) consumption invoice that is balanced out in a later meter-based invoice;
*	Pre-payment (with or without VAT) is settled through a final invoice; and
* Some user communities prefer to use negative invoice rather than credit note when correcting transactions.

====
NOTE: Buyers who value automatic matching of e-invoices to orders or invoicing objects may wish to limit the areas and situations where complex transactions can be accepted and voice their requirements at time of procurement.
====

The decision has the following implications on the transaction format:

* The invoice (now with “negative invoice capacity”) can function as an alternative to the credit note. Invoice-generating systems may implement either option, while invoice-receiving systems have to support both of them.
*	The transaction format for credit note has to be designed to accommodate for negative grand total, as well; this is because an entire negative invoice may have to be balanced out by means of a credit note.

Attention is drawn to the intrinsic differences between credit note and negative invoice when it comes to convey crediting information.


include::../../syntax/negative-invoices.adoc[]
