

= Seller (AccountingSupplierParty)

Seller is mandatory information and provided in element `cac:AccountingSupplierParty`

.UBL example of seller information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=seller]
----
<1> schemeID attribute is mandatory for electronic addresses, ie. EndpointID
<2> schemeID attribute is recommended for all party identifiers
<3> VAT identifiers shall be prefixed with the country code



= Buyer (AccountingCustomerParty)

Buyer is mandatory information and provided in element `cac:AccountingCustomerParty`

.UBL example ofbuyer information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=buyer]
----
<1> schemeID attribute is mandatory for electronic addresses, ie. EndpointID
<2> schemeID attribute is recommended for all party identifiers
<3> VAT identifiers shall be prefixed with the country code
<4> schemeID attribute is recommended for party legal entity identifiers


= Payment receiver (PayeeParty)

Payment receiver is optional information. If this information is not supplied, the seller is the payment receiver. When payee information is sent this is indicating that a factoring situation is being documented.

To reflect the assignment of an Invoice to a factor there is a need to:

. have a disclaimer (notification notice) on the Invoice that the Invoice has been assigned to a factor. The disclaimer should be given using the Invoice note (BT-22) on document level.

. identify the Factor as the Payee

. to have the bank account changed to favour of a Factor.


.UBL example of payee information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=payee]
----
<1> schemeID attribute is recommended for all party identifiers
<2> schemeID attribute is recommended for party legal entity identifiers


= Sellers Tax Representative (TaxRepresentativePary)

Tax representative party for the seller is relevant for sellers delivering goods and services in a country without having a permanent establishment in that country. In such cases information on the tax representative shall be included in the invoice.

.UBL example of tax representative information
[source, xml, indent=0]
----
include::{snippet-dir}/Snippet-full.xml[tags=taxrep]
----
<1> VAT identifiers shall be prefixed with the country code
