
[[totals]]
== UBL syntax calculation formulas

The following elements show the legal monetary totals for an invoice or credit note
[cols="3,5", options="header"]
|===
| Element
| Formula

| <cbc:LineExtensionAmount>
| stem:[sum("cac:InvoiceLine/cbc:LineExtensionAmount")]

| <cbc:AllowanceTotalAmount>
| stem:[sum("cac:AllowanceCharge[ChargeIndicator='false'$$]$$/cbc:Amount")]

| <cbc:ChargeTotalAmount>
| stem:[sum("cac:AllowanceCharge[ChargeIndicator='true'$$]$$/cbc:Amount")]

| <cbc:TaxExclusiveAmount>
| stem:[\ \ \ \ "cac:LegalMonetaryTotal/cbc:LineExtensionAmount"] +
stem:[– \ "cac:LegalMonetaryTotal/cbc:AllowanceTotalAmount"] +
stem:[+ \ "cac:LegalMonetaryTotal/cbc:ChargeTotalAmount"]

| <cbc:TaxInclusiveAmount>
| stem:[\ \ \ \ "cac:LegalMonetaryTotal/cbc:TaxExclusiveAmount"] +
stem:[+ \ "cac:TaxTotal/cbc:TaxAmount"]

| <cbc:PrepaidAmount>
| _Not applicable_

| <cbc:PayableRoundingAmount>
| _Not applicable_

| <cbc:PayableAmount>
| stem:[\ \ \ \ "cac:LegalMonetaryTotal/cbc:TaxInclusiveAmount"] +
stem:[- \ "cac:LegalMonetaryTotal/cbc:PrepaidAmount"] +
stem:[+ \ "cac:LegalMonetaryTotal/cbc:PayableRoundingAmount"]
|===



== Element for rounding amount, the PayableRoundingAmount

It is possible to round the expected payable amount.

The element `cac:LegalMonetaryTotal/cbc:PayableRoundingAmount` is used for this purpose and is specified on the header level. This value shall be added to the value in `cac:LegalMonetaryTotal/cbc:PayableAmount`.

Example:  Amount  999.81 rounded to  1000.  PayableRounding Amount = 0.19
