[[element-codes]]
= Code lists for coded elements

:leveloffset: +1


include::invoice-types-en.adoc[]
include::credit-note-types-en.adoc[]


= Common code lists for both the invoice and the credit note transaction

== Currency code

All currencies must be from link:https://www.iso.org/iso-4217-currency-codes.html[ISO 4217:2015]


== Value added tax point date code

A subset of values from  link:http://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred2005.htm[UN/CEFACT code list 2005, D.16B] must be used. Valid values are listed in the table below:

[cols="1,4", options="header"]
.Code list
|===
| Code
| Description

| 3
| Invoice document issue date time

| 35
| Paid to date

| 432
| Standard rate
|===


== Country code

All country codes in an invoice or credit note must be the alpha-2 code from link:http://www.iso.org/iso/home/standards/country_codes.htm[ISO 3166-1]


== Payment means type code

Payment means type code must be from link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred4461.htm[UN/CEFACT code list 4461, D.16B]


== VAT category codes

A subset of values from  link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5305.htm[UN/CEFACT code list 5305, D.16B] must be used. Valid values are listed in the table below:

[cols="1,4", options="header"]
.Code list
|===
| Code
| Description

| AE
| Vat Reverse Charge

| E
| Exempt from Tax

| S
| Standard rate

| Z
| Zero rated goods

| G
| Free export item, tax not charged

| O
| Services outside scope of tax

| K
| VAT exempt for EEA intra-community supply of goods and services

| L
| Canary Islands general indirect tax

| M
| Tax for production, services and importation in Ceuta and Melilla
|===

== Allowance reason codes

Any allowance reason codes must be from link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred5189.htm[UN/CEFACT code list 5189, D.16B] +
#Should we restrict to allowance codes only?#

== Charge reason codes

Any charge reason codes must be from
 link:https://www.unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred7161.htm[UN/CEFACT code list 7161, D.16B] +
 #Should we restrict to charge codes only?#


== VAT exemption reason code

{EN16931} states _Code list issued and maintained by CEF_ +
#Code list not available.#

== Mime code of attached document

Subset of link:http://www.iana.org/assignments/media-types[IANA]. Valid values are listed in the table below.

[cols="1,4"]
.Code list
|===

.1+h| Documents
| application/pdf

.2+h| Images
| image/png
| image/jpeg


.1+h| Text
| text/csv

.2+h| Spreadsheet
| application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
| application/vnd.oasis.opendocument.spreadsheet
|===


== Unit of measure

Valid unit codes must be from  link:http://www.unece.org/tradewelcome/un-centre-for-trade-facilitation-and-e-businessuncefact/outputs/cefactrecommendationsrec-index/list-of-trade-facilitation-recommendations-n-16-to-20.html[UN/ECE Recommendation 20, Revision 8 (2012)]


:leveloffset: -1
