[preface]
= Introduction to openPEPPOL and BIS


This {peppol} BIS provides a set of specifications for implementing a {peppol} business process.

This specification, is a Core Invoice Usage Specification (CIUS) of {EN16931}, following the guidance given in chapter 7 of the {EN16931}. Any instance documents compliant to this specification will be compliant with the European Standard ({EN16931}).

The purpose of this document is to facilitate an efficient implementation and increased use of electronic collaboration regarding the billing process.


.Statement of copyright
****
This PEPPOL Business Interoperability Specification (PEPPOL BIS) document is a Core Invoice Usage Specification (CIUS) based on CEN/EN 16931:2017. The restrictions on CEN/EN 16931:2017 implemented in this PEPPOL BIS appear from the conformance statement provided in appendix A.

The copyright of CEN/EN 16931:2107 is owned by CEN and its members - the European National Standards Bodies. A copy of CEN/EN 16931-1:2017 may be obtained free of charge from any CEN member.

OpenPEPPOL AISBL holds the copyright of this PEPPOL BIS, developed and published subject to the conditions of the agreement between the European Commission and CEN allowing derivate works to be developed and distributed with no additional licensing requirements. CEN and the National  Standards Bodies bears no liability from the content and implementation of this PEPPOL BIS.

This PEPPOL BIS document may not be modified, re-distribute, sold or repackaged in any other way without the prior consent of OpenPEPPOL AISBL.
****


== Document Structure

This document is structured as follows:

*	*Chapters 1 - 5* gives general information on the business processes, requirements and functionalities
*	*Chapter 6* describes the semantical data types
*	*Chapters 7 - 9* describes VAT, calculations and rounding.
*	*Chapter 10* provides examples of selected parts of the invoice
*	*Chapter 11* gives details and links to all code lists used
* *Chapter 12* gives information on PEPPOL identifiers
*	*Chapter 13* describes in detail central information elements.
*	*Chapters 14 and 15* provides information on validation and validation rules
*	*Annexes* give information on restrictions according to {EN16931}, use of Cross Industry Invoice syntax and national and syntax rules.

== Scope

This document is concerned with clarifying requirements for ensuring interoperability  and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

== Audience

The audience for this document is organisations wishing to be PEPPOL enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on PEPPOL/OpenPEPPOL, please see {common}
