[preface]
= Introduction to openPEPPOL and BIS


This {peppol} BIS provides a set of specifications for implementing a {peppol} business process.

This specification, is a Core Invoice Usage Specification (CIUS) of {EN16931}, following the guidance given in chapter 7 of the {EN16931}. Any instance documents compliant to this specification will be compliant with the European Standard ({EN16931}).

Implementers must purchase copies (licences) of the relevant parts of EN 16931, which as a minimum will include:

* *EN 16931-1:2017 - Electronic invoicing* - Part 1: Semantic data model of the core elements of an electronic invoice ({EN16931})
* *CEN/TS 16931-3-2:2017 Electronic invoicing* - Part 3-2: Syntax binding for ISO/IEC 19845 (UBL 2.1) invoice and credit note ({ubl-binding})
* *CEN/TS 16931-3-3:2017 Electronic invoicing* - Part 3-3: Syntax binding for UN/CEFACT XML Industry Invoice D16B ({cii-binding})

CEN lists sales points for these specifications under the {TC434-docs}[CEN/TC 434 Published Standards section].

The purpose of this document is to facilitate an efficient implementation and increased use of electronic collaboration regarding the billing process.

== Document Structure

This document is structured as follows:

*	*Chapters 1 - 5* gives general information on the business processes, requirements and functionalities
*	*Chapter 6* describes the semantical data types
*	*Chapters 7 - 9* describes VAT, calculations and rounding.
*	*Chapter 10* provides examples of selected parts of the invoice
*	*Chapter 11* gives details and links to all code lists used
* *Chapter 12* gives information on PEPPOL identifiers
*	*Chapter 13* describes in detail central information elements.
*	*Chapters 14 and 15* provides information on validation and validation rules
*	*Annexes* give information on restrictions according to {EN16931}, use of Cross Industry Invoice syntax and national and syntax rules.

== Scope

This document is concerned with clarifying requirements for ensuring interoperability  and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

== Audience

The audience for this document is organisations wishing to be PEPPOL enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on PEPPOL/OpenPEPPOL, please see {common}
