[preface]
= Introduction to openPEPPOL and BIS


This {peppol} BIS provides a set of specifications for implementing a {peppol} business process.

This specification, is a Core Invoice Usage Specification (CIUS) of {EN16931}, following the guidance given in chapter 7 of the {EN16931}. Any instance documents compliant to this specification will be compliant with the European Standard ({EN16931}).

The purpose of this document is to facilitate an efficient implementation and increased use of electronic collaboration regarding the billing process.

== Document Structure

This document consists of the following chapters and contents:

*	Chapter 1 gives a short introduction describing the background and objective of this implementation guide.
*	Chapter 2 gives the change history of the document.
*	Chapter 3 describes the EHF formats (Invoice and Credit note) in general.
*	Chapter 4 links to definitions relevant to EHF formats.
*	Chapter 5 links to general principles and conditions for the formats.
*	Chapter 6 describes in detail central information elements.
*	Chapter 7 deals with validation.
*	Chapter 8 embraces appendices.

== Scope

This document is concerned with clarifying requirements for ensuring interoperability  and provides guidelines for the support and implementation of these requirements. This document will also provide a detailed implementation guideline for the invoice and credit note transactions.

== Audience

The audience for this document is organisations wishing to be PEPPOL enabled for exchanging electronic invoices, and/or their ICT-suppliers. These organisations may be:

     * Service providers
     * Contracting Authorities (CA)
     * Economic Operators (EO)
     * Software Developers

More specifically, roles addressed are the following:

    * ICT Architects
    * ICT Developers
    * Business Experts

For further information on PEPPOL/OpenPEPPOL, please see {common}
